### ISSUE TITLE
Create better connection management

### ISSUE THREAD

**Issue by macat** [namely/arnoldb-client-ruby#17]
- [ ] DNS based discovery
- [ ] Reconnecting after failure

**Comment by poopoothegorilla** [comment]
@macat is this still needed? or does kubernetes take care of reconnecting. For the DNS based discovery were you talking about this idea https://github.com/namely/arnoldb/issues/103? or is this something else?

**Comment by macat** [comment]
No this is not needed as we are going to fully deploy it in kubernetes. Closing it.
